export type BacktestSource = "congress" | "form4" | "contracts" | "lobbying";
export type BacktestRules = {
  entry: "nextOpen" | "nextClose";
  holdDays: number;
  stopLossPct: number | null;
  takeProfitPct: number | null;
  sides: "buy" | "sell" | "both";
  sizing: "equal" | "amountMid";
  benchmark: string;
  costBps: number;
  slippageBps: number;
  openTrades: "exclude" | "mark";
};
export type BacktestFilters = {
  member: string;
  party: "" | "D" | "R" | "I";
  chamber: "" | "house" | "senate";
  committee: string;
  tickers: string[];
  sector: string;
  from: string;
  to: string;
  minAmount: number;
  nearHearingDays: number;
  hearingKnown: boolean;
  minLagDays: number;
  maxLagDays: number;
  contractAgency: string;
  contractLagDays: number;
  include10b51: boolean;
  excludeMembers: string[];
  spikePct: number;
};
export type BacktestSpec = { source: BacktestSource; filters: BacktestFilters; rules: BacktestRules };

export const SOURCES: BacktestSource[];
export const SOURCE_LABEL: Record<BacktestSource, string>;
export const SECTOR_ETF: Record<string, string>;
export const SECTOR_ETFS: string[];
export const BENCHMARKS: string[];
export const BENCHMARK_LABEL: Record<string, string>;
export const LIMITS: { holdDays: [number, number]; pct: [number, number]; bps: [number, number]; hearingDays: [number, number]; signals: number; tickers: number; minAmount: number };
export const DEFAULT_RULES: BacktestRules;
export const DEFAULT_FILTERS: BacktestFilters;
export function cleanRules(raw: unknown): BacktestRules;
export function cleanFilters(raw: unknown): BacktestFilters;
export function cleanSpec(raw: unknown): { ok: true; spec: BacktestSpec } | { ok: false; error: string };
export function specKey(spec: unknown): string;
export function specHash(spec: unknown): string;
export function encodeSpec(spec: unknown): string;
export function decodeSpec(token: string): BacktestSpec | null;
export function describeSpec(spec: BacktestSpec): string;
