export type CardSummary = {
  bioguide: string;
  name: string;
  slug: string;
  party: string;
  state: string;
  chamber: string;
  seat: string;
  title: string;
  trades: number;
  buys: number;
  sells: number;
  first: string;
  last: string;
  medianLag: number | null;
  late: number;
  maxLag: number | null;
  nearDays: number;
  hasLanes: boolean;
  dayShare: number | null;
  baseline: number | null;
  returns: { buys: number; priced: number; excess: number | null; excess90: number | null; hit: number | null; basis: string } | null;
  range: { from: string; to: string };
  asOf: string;
  strip: { d: string; side: string; near: boolean; low: number }[];
};

export const CARD_W: number;
export const CARD_H: number;
export const LATE_DAYS: number;
export function shortDate(iso: string): string;
export function escapeXml(value: unknown): string;
export function memberSlug(name: string): string;
export function seatLabel(m: { party?: string; state?: string; district?: string; chamber?: string }): string;
export function summarize(res: unknown): CardSummary | null;
export function describe(s: CardSummary | null): string;
export function memberMeta(s: CardSummary, opts: { pageUrl: string; imageUrl: string; site?: string }): { title: string; description: string; url: string; image: string; site: string };
export function cardSvg(s: CardSummary, opts?: { site?: string; host?: string }): string;
export function memberPageHtml(s: CardSummary, opts: { pageUrl: string; imageUrl: string; appPath: string; site?: string }): string;
